name: xarray
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh>=2.0.0
  - cartopy
  - dask=2.20.0
  - dask-labextension>=2.0.0
  - distributed=2.20.0
  - fsspec
  - gcsfs
  - geoviews
  - gsw
  - hvplot
  - ipywidgets>=7.5
  - jupyter-server-proxy
  - jupyterlab>=2.0.0
  - matplotlib
  - notebook
  - nodejs
  - netcdf4
  - numpy>=1.18.1
  - pandas>=1.0.1
  - pydap
  - python-graphviz
  - scipy>=1.3.0
  - zarr
  - pip
  - pip:
    - expectexception
