name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
  test:
    name: Tutorial Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install graphviz
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
      - name: Set up Python 3.8
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: xarray
           environment-file: .binder/environment.yml
           python-version: 3.8
           auto-activate-base: false
      - name: Update conda environment
        shell: bash -l {0}
        run: |
          conda env update --file ./ci/environment.yml
      - name: Build and test notebooks
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python .tests/nbrun.py
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install repo2docker
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter-repo2docker
      - name: Build xarray-tutorial Docker image
        run: jupyter-repo2docker --no-run --debug .
