name: PR Preview

on: [pull_request_target]

permissions:
  pull-requests: write # allow surge-preview to create/update PR comments

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    env:
      PREVIEW_URL: https://{{repository.owner}}-{{repository.name}}-{{job.name}}-pr-{{pr.number}}.surge.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JupyterBook Cache
        uses: actions/cache@v4
        with:
          path: _build
          # NOTE: change key to "jupyterbook-DATE" to force rebuilding cache
          key: jupyterbook-20240517

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/conda-lock.yml
          environment-name: xarray-tutorial
          cache-environment: true

      - name: Build JupyterBook
        # NOTE: login shell activates conda environment
        shell: bash -l {0}
        run: |
          jupyter-book build ./ --warningiserror --keep-going

      - name: Dump Build Logs
        if: always()
        run: |
          if (test -a _build/html/reports/*log); then cat _build/html/reports/*log ; fi

      - name: Install Surge.sh
        uses: actions/setup-node@v4

      - run: npm install -g surge

      - run: surge ./_build/html {{env.PREVIEW_URL}} --token $SURGE_TOKEN
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Add URL to Summary
        run: |
          echo "#### :rocket: Preview deployed at {{env.PREVIEW_URL}}" >> $GITHUB_STEP_SUMMARY
